file_uploader/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('upload_form.urls', namespace = 'upload_form')),
]

upload_form/urls.py
from django.conf.urls import url
from upload_form import views

urlpatterns = [
    url(r'^$', views.form, name = 'form'),
    url(r'^complete/', views.complete, name = 'complete'),
    url(r'^choice_column/', views.choice_column, name = 'choice_column'),
    url(r'^result/', views.result, name = 'result'),
]

upload_form/models.py
from django.db import models

# Create your models here.
from datetime import datetime

class FileNameModel(models.Model):
    file_name = models.CharField(max_length = 50)
    upload_time = models.DateTimeField(default = datetime.now)
    file_obj = models.FileField(upload_to = 'upload_form/static/files/')
    
class ImageURLModel(models.Model):
    image_url_name = models.URLField()
    upload_time = models.DateTimeField(default = datetime.now)
    
class BudgetModel(models.Model):
    budget = models.IntegerField()

upload_form/forms.py
from django import forms

class DfColumnForm(forms.Form):

        df_columns = forms.ChoiceField(
        label='df_columns',
        widget=forms.CheckboxSelectMultiple,
        choices=[],
        required=True,
    )
        df_date = forms.ChoiceField(
        label='df_date',
        widget=forms.CheckboxSelectMultiple,
        choices=[],
        required=True,
    )
        df_budget = forms.IntegerField(
        label='df_budget',
        #default=int(1000),
        required=True,
    )
        df_goal = forms.ChoiceField(
        label='df_goal',
        widget=forms.CheckboxSelectMultiple,
        choices=[],
        required=True,
    )
        df_control = forms.ChoiceField(
        label='df_control',
        widget=forms.CheckboxSelectMultiple,
        choices=[],
        required=True,
    )
                
                

upload_form/views.py
# Create your views here.
from django.shortcuts import render, redirect
from django.template.context_processors import csrf
from django.conf import settings
from upload_form.models import FileNameModel
from upload_form.models import ImageURLModel
from upload_form.models import BudgetModel
import sys, os
import pandas as pd
from . import forms as forms
from . import calculate as cl
from django import forms as fm_d
UPLOADE_DIR = os.path.dirname(os.path.abspath(__file__)) + '/static/files/'

###ファイルアップロード関数
def form(request):
    
    #通常時form.htmlを表示
    if request.method != 'POST':
        return render(request, 'upload_form/form.html')
    
    #ファイル取得し、データをcsv_dataに格納
    file = request.FILES['file']
    path = os.path.join(UPLOADE_DIR, file.name)
    destination = open(path, 'wb')
    
    '''#Fileをアップロード先に保存
    for chunk in file.chunks():
        destination.write(chunk)
    destination.close()'''
    
    #File名をサーバーに保存
    insert_data = FileNameModel(file_name = file.name,file_obj = file)
    insert_data.save()
    
    return redirect('upload_form:choice_column')
    #return render(request,'upload_form/complete.html',data)


###ファイルアップロード完了関数
def complete(request):
    
    return render(request, 'upload_form/complete.html')

###アップしたファイルのカラム名からアロケしたい要素を選択
def choice_column(request):
    
    #データベースに格納されたファイルオブジェクトを抽出→URLを抽出→ファイルデータを格納
    temp = FileNameModel.objects.latest('id')
    csv_data = pd.read_csv(temp.file_obj.url, encoding = 'ms932')

    #選択されたファイルのカラム名をリスト化(アロケ粒度用)
    group1 = []
    for factor in csv_data.select_dtypes(exclude=['number']).columns:
        group1.append((factor,factor))
        
    #選択されたファイルのカラム名をリスト化(Day選択用)
    group2 = []
    for factor in csv_data.select_dtypes(exclude=['number']).columns:
        group2.append((factor,factor))          
        
    #選択されたファイルのカラム名をリスト化(最大化項目選択用)
    group3 = []
    for factor in csv_data.select_dtypes(include=['number']).columns:
        group3.append((factor,factor))  
        
    #選択されたファイルのカラム名をリスト化(入力項目選択用)
    group4 = []
    for factor in csv_data.select_dtypes(include=['number']).columns:
        group4.append((factor,factor))

    #forms.pyで定義されたフォームをファイルのカラム名で再定義
    form = forms.DfColumnForm()
    form.fields['df_columns'].choices = group1
    form.fields['df_date'].choices = group2
    form.fields['df_goal'].choices = group3
    form.fields['df_control'].choices = group4

    #選択されたカラム名/date項目を受け取り
    obj_choices = request.POST.getlist('df_columns')
    obj_date = request.POST.getlist('df_date')
    obj_goal = request.POST.getlist('df_goal')
    obj_control = request.POST.getlist('df_control')
    
    image_url = ''

    ###計算結果
    if obj_choices:
        obj_budget = request.POST['df_budget']
        insert_budget = BudgetModel(budget = obj_budget)
        insert_budget.save()
        result,images,result_file_name = cl.calculate(obj_choices,obj_date,obj_goal,obj_control,int(obj_budget))
        ##シミュレーション結果をデータベースへ保存
        insert_data_image = ImageURLModel(image_url_name = result_file_name)
        insert_data_image.save()

        return redirect('upload_form:result')
    else:
        obj_budget = ''
        result = ''
        images = ''
        budget_for_print = ''

    data = {
        'input_data' : form,
        'budget_for_print' : budget_for_print,
    }
    
    return render(request,'upload_form/choice_column.html',data)

def result(request):
    
    temp = ImageURLModel.objects.latest('id')
    csv_data = pd.read_csv(temp.image_url_name, encoding = 'utf-8')   
    '''excel = pd.ExcelFile(temp.image_url_name,encoding = 'ms932')
    sheet_name = excel.sheet_names
    csv_data= excel.parse()'''
    images = csv_data['graph_url']
    image_names = csv_data['graph_name']
    
    budget = BudgetModel.objects.latest('id')
    data = {
            'images' : images,
        'image_names' : image_names,
            'budget' : budget.budget,
        
    }
    
    return render(request,'upload_form/result.html',data)

upload_form/templates/upload_form/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="viewport" content="content">
        <meta charset="UTF-8">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <link rel='stylesheet' href='http://cdn.rawgit.com/JeremyFagis/dropify/master/dist/css/dropify.css' />  

        <script src='http://cdn.rawgit.com/JeremyFagis/dropify/master/dist/js/dropify.js'></script> 
        <script src="https://cdn.rawgit.com/sindu12jun/table-dragger/dev/dist/table-dragger.min.js"></script>
        <title>ファイルアップローダ</title>
    </head>
    <body>
        {% block content %}
        {{content}}
        {% endblock %}
    </body>
</html>

upload_form/templates/upload_form/choice_column.html
{% extends "upload_form/base.html" %}

{% block title %}アップロード完了{% endblock title %}
{% block content %}
<div>
    <p>↓から予算配分したい粒度を選択してください</p>
</div>
        <form method="POST" enctype="multipart/form-data">
            <div class="ui-field-contain">
        {% csrf_token %}
            <fieldset data-role="controlgroup" data-type="horizontal">
            <table id="table">
        {% for column1 in input_data.df_columns%}
                <th class="handle">{{column1}}</th>
        {%endfor%}
            </table>
                </fieldset>
            <script>tableDragger(document.querySelector("#table"));</script>
        <div>
        <p>↓日付項目を選択してください</p>
        <fieldset data-role="controlgroup" data-type="horizontal">
        {% for column2 in input_data.df_date%}
        {{column2}}
        {%endfor%}
            </fieldset>
        </div>
        <div>
        <p>↓最大化する項目を選択してください</p>
        <fieldset data-role="controlgroup" data-type="horizontal">
        {% for column3 in input_data.df_goal%}
        {{column3}}
        {%endfor%}
            </fieldset>
        </div>
        <div>
        <p>↓金額の項目を選択してください</p>
        <fieldset data-role="controlgroup" data-type="horizontal">
        {% for column4 in input_data.df_control%}
        {{column4}}
        {%endfor%}
            </fieldset>
        </div>
        <div>
            <p>↓配分する総予算を入力してください</p>
        ¥{{input_data.df_budget}}
        </div>
        <input type="submit" value="Simlation"　name="choices">  
            </div>
    </form>

<div align="center">
<a href="{% url 'upload_form:form' %}"><button>戻る</button></a>
</div>
{% endblock content %}

upload_form/templates/upload_form/complete.html
{% extends "upload_form/base.html" %}

{% block title %}アップロード完了{% endblock title %}
{% block content %}
    <div align="center">
        <h1 align="center">アップロード完了</h1>
        <a href="{% url 'upload_form:choice_column' %}"><button>戻る</button></a>
        {{db}}
    </div>
{% endblock content %}

upload_form/templates/upload_form/form.html
{% extends "upload_form/base.html" %}

{% block title %}アップローダサンプル{% endblock title %}
{% block content %}

<div>
    <p>予算配分を行うファイルをアップロードしてください</p>
    </div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file"  class="dropify" name="file">
        <input type="submit" value="アップロード">        
    </form>

        <script>
$('.dropify').dropify();
</script>

{% endblock content %}

upload_form/templates/upload_form/result.html
{% extends "upload_form/base.html" %}

{% block title %}アップロード完了{% endblock title %}
{% block content %}

    <div align="center">
        <h1 align="center">結果出力</h1>
        <div>
            予算：¥{{budget}}
        </div>
        <div>
        <table border = 1>
        <tr>
        {% for image in image_names %}
            <td><center>{{image}}</center></td>
        {%endfor%}
        </tr>
        <tr>
        {% for image in images %}
            <td><img src ="{{image}}" width = "250"></td>
        {%endfor%}
        </tr>
        </table>
        </div>
        <div>
        <a href="{% url 'upload_form:form' %}"><button>戻る</button></a>
        </div>
    </div>
{% endblock content %}

upload_form/templates/upload_form/table-dragger-dev/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="description" content="table-dragger, drag and sort rows or columns of table">
  <meta name="author" content="sindu12jun">
  <title>sindu12jun-TableDragger</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.4.1/themes/prism-tomorrow.min.css">

  <style>
    .btn {
      border: 2px solid;
    }

    footer a,
    footer a:hover,
    .jumbotron a,
    .jumbotron a:hover {
      color: #cc99cd;
    }

    footer, .jumbotron {
      margin-bottom: 0;
      background: #2d2d2d;
      color: #67cdcc;
    }

    footer {
      margin-top: 1em;
      padding: 1em 0;
      color: #ccc;
    }

    .handle {
      font-family: 'Glyphicons Halflings';
      color: #dd5;
    }

    .handle:hover {
    }

    .handle:before {
      content: "\e068";
    }

    .sortable-ghost {
      background: #efefef;
    }

    section {
      margin-bottom: 40px;
    }

    /*.tbl-header {*/
    /*background-color: rgba(255, 255, 255, 0.3);*/
    /*}*/

    /*td, th {*/
    /*background-color: #67CDCC;*/
    /*padding: 15px;*/
    /*text-align: left;*/
    /*vertical-align: middle;*/
    /*font-weight: 300;*/
    /*font-size: 16px;*/
    /*color: #fff;*/
    /*border-bottom: solid 1px rgba(255, 255, 255, 0.1);*/
    /*}*/

    table {
      table-layout: fixed;
      width: 100%;
    }

    .sindu-table {
      background: #34495E;
      color: #fff;
      overflow: hidden;
    }

    .sindu-table th {
      padding: 16px;
      color: #dd5;
    }

    .sindu-table td {
      padding: 16px;
    }
  </style>
</head>
<body>
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-2">
        <a href="https://github.com/sindu12jun/table-dragger"><h1>table-dragger</h1></a>
        <p class="lead">
          Easily add drag-and-drop sorting to your table without jQuery
          <a href="https://github.com/sindu12jun/table-dragger" class="btn btn-lg">View on GitHub</a>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h2 class="page-header">Usage
        <span class="small">
          cells that can be lifted up was marked with icon <i class="handle"></i>
        </span>
      </h2>
      <section>
        <h4>Default <span class="small">With no options, sort columns, handler was the first row</span></h4>
        <table id="default-table" class="sindu-table">
          <thead>
          <tr>
            <th>Movie Title<i class="handle"></i></th>
            <th>Genre<i class="handle"></i></th>
            <th>Year<i class="handle"></i></th>
            <th>Gross<i class="handle"></i></th>
          </tr>
          </thead>
          <tr>
            <td>Star Wars</td>
            <td>Adventure, Sci-fi</td>
            <td>1977</td>
            <td>$460,935,665</td>
          </tr>
          <tr>
            <td>Howard The Duck</td>
            <td>"Comedy"</td>
            <td>1986</td>
            <td>$16,295,774</td>
          </tr>
          <tr>
            <td>American Graffiti</td>
            <td>Comedy, Drama</td>
            <td>1973</td>
            <td>$115,000,000</td>
          </tr>
        </table>
        <pre>
          <code class="language-javascript">
tableDragger(document.querySelector(&#x22#default-table&#x22));
        </code>
        </pre>
      </section>

      <section>
        <h4>Sort Rows <span class="small">Sort rows, handler was the first column</span></h4>
        <table id="row-table" class="sindu-table">
          <thead>
          <tr>
            <th>Movie Title<i class="handle"></i></th>
            <th>Genre</th>
            <th>Year</th>
            <th>Gross</th>
          </tr>
          </thead>
          <tr>
            <td>Star Wars<i class="handle"></i></td>
            <td>Adventure, Sci-fi</td>
            <td>1977</td>
            <td>$460,935,665</td>
          </tr>
          <tr>
            <td>Howard The Duck<i class="handle"></i></td>
            <td>"Comedy"</td>
            <td>1986</td>
            <td>$16,295,774</td>
          </tr>
          <tr>
            <td>American Graffiti<i class="handle"></i></td>
            <td>Comedy, Drama</td>
            <td>1973</td>
            <td>$115,000,000</td>
          </tr>
        </table>
        <pre>
          <code class="language-javascript">
tableDragger(document.querySelector(&#x22#row-table&#x22), { mode: &#x22row&#x22 });
        </code>
        </pre>
      </section>

      <section>
        <h4>Handler <span class="small">Specify drag handler wherever within the table</span></h4>
        <table id="handle-table" class="sindu-table">
          <thead>
          <tr>
            <th>Movie Title <i class="handle">dragme</i></th>
            <th>Genre</th>
            <th>Year</th>
            <th>Gross</th>
          </tr>
          </thead>
          <tr>
            <td>Star Wars</td>
            <td>Adventure, Sci-fi</td>
            <td>1977</td>
            <td>$460,935,665</td>
          </tr>
          <tr>
            <td>Howard The Duck</td>
            <td>"Comedy"</td>
            <td>1986</td>
            <td>$16,295,774</td>
          </tr>
          <tr>
            <td>American Graffiti</td>
            <td>Comedy, Drama</td>
            <td>1973</td>
            <td>$115,000,000</td>
          </tr>
        </table>
        <pre>
          <code class="language-javascript">
tableDragger(document.querySelector(&#x22#row-table&#x22), { dragHandler: &#x22.handle&#x22 });
        </code>
        </pre>
      </section>

      <section>
        <h4>Free <span class="small">After mousedown, move mouse horizontally or vertically, see what happens. Don't forget to specify drag handler</span>
        </h4>
        <table id="free-table" class="sindu-table">
          <thead>
          <tr>
            <th>Movie Title</th>
            <th>Genre</th>
            <th>Year</th>
            <th>Gross</th>
          </tr>
          </thead>
          <tr>
            <td>Star Wars<i class="handle">dragme</i></td>
            <td>Adventure, Sci-fi</td>
            <td>1977</td>
            <td>$460,935,665</td>
          </tr>
          <tr>
            <td>Howard The Duck</td>
            <td>"Comedy"</td>
            <td>1986</td>
            <td>$16,295,774</td>
          </tr>
          <tr>
            <td>American Graffiti</td>
            <td>Comedy, Drama</td>
            <td>1973</td>
            <td>$115,000,000</td>
          </tr>
        </table>
        <pre>
          <code class="language-javascript">
tableDragger(document.querySelector(&#x22#row-table&#x22), { mode: &#x22row&#x22, onlyBody: true, dragHandler: &#x22.handle&#x22 });
        </code>
        </pre>
      </section>

      <section>
        <h4>Only Body <span class="small">Setting onlyBody to true in row mode, user can only lift rows in tBody</span>
        </h4>
        <table id="only-body-table" class="sindu-table">
          <thead>
          <tr>
            <th>Movie Title</th>
            <th>Genre</th>
            <th>Year</th>
            <th>Gross</th>
          </tr>
          </thead>
          <tr>
            <td>Star Wars<i class="handle"></i></td>
            <td>Adventure, Sci-fi</td>
            <td>1977</td>
            <td>$460,935,665</td>
          </tr>
          <tr>
            <td>Howard The Duck<i class="handle"></i></td>
            <td>"Comedy"</td>
            <td>1986</td>
            <td>$16,295,774</td>
          </tr>
          <tr>
            <td>American Graffiti<i class="handle"></i></td>
            <td>Comedy, Drama</td>
            <td>1973</td>
            <td>$115,000,000</td>
          </tr>
        </table>
        <pre>
          <code class="language-javascript">
tableDragger(document.querySelector(&#x22#row-table&#x22), { mode: &#x22row&#x22, onlyBody: true });
        </code>
        </pre>
      </section>

      <section>
        <h4>Event <span class="small">Add callback when event trigger, open devtool see what happens</span></h4>
        <table id="event-table" class="sindu-table">
          <thead>
          <tr>
            <th>Movie Title</th>
            <th>Genre</th>
            <th>Year</th>
            <th>Gross</th>
          </tr>
          </thead>
          <tr>
            <td>Star Wars <i class="handle">dragme</i></td>
            <td>Adventure, Sci-fi</td>
            <td>1977</td>
            <td>$460,935,665</td>
          </tr>
          <tr>
            <td>Howard The Duck</td>
            <td>"Comedy"</td>
            <td>1986</td>
            <td>$16,295,774</td>
          </tr>
          <tr>
            <td>American Graffiti</td>
            <td>Comedy, Drama</td>
            <td>1973</td>
            <td>$115,000,000</td>
          </tr>
        </table>
        <pre>
          <code class="language-javascript">
tableDragger(document.querySelector('#event-table'), { mode: 'free', dragHandler: '.handle', onlyBody: true })
  .on('drag', () => {
    console.log('drag');
  })
  .on('drop', (from, to, el, mode) => {
    console.log(`drop ${el.nodeName} from ${from} ${mode} to ${to} ${mode}`);
  })
  .on('shadowMove', (from, to, el, mode) => {
    console.log(`move ${el.nodeName} from ${from} ${mode} to ${to} ${mode}`);
  })
  .on('out', (el, mode) => {
    console.log(`move out or drop ${el.nodeName} in mode ${mode}`);
  });
        </code>
        </pre>
      </section>
    </div>
  </div>
</div>

<footer>
  <div class="container text-center">
    <small>Free to Use Under The MIT License (MIT) | Created by <a href="https://github.com/sindu12jun">@sindu12jun</a>
    </small>
  </div>
</footer>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.4.1/prism.min.js"></script>
<script src="./build/build-docs.js"></script>
</body>
</html>